[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "pydantic-pint"
description = "Pydantic Validation for Pint Quantities."
authors = [
    {name = "Tyler Hughes", email = "tylerxh111+git@proton.me"},
]
readme = "README.md"
license = { file = "LICENSE.md" }
requires-python = ">=3.8"
keywords = [
    "pydantic-pint",
    "pydantic",
    "pint",
]
classifiers = [
    "Development Status :: 1 - Planning",
    "Framework :: Pydantic",
    "Framework :: Pydantic :: 2",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]
dependencies = [
    "pint>=0.20",
    "pydantic>=2.0",
    "typing-extensions>=3.7.4 ; python_full_version < '3.9'"
]
dynamic = [
    "version",
]

[project.urls]
source        = "https://github.com/tylerh111/pydantic-pint"
issues        = "https://github.com/tylerh111/pydantic-pint/issues"
changes       = "https://github.com/tylerh111/pydantic-pint/blob/main/CHANGES.md"
documentation = "https://pydantic-pint.readthedocs.io"

[dependency-groups]
all = [
    { include-group = "dev"   },
    { include-group = "docs"  },
    { include-group = "build" },
    { include-group = "lint"  },
    { include-group = "test"  },
]
dev = [
    "rust-just",
    "setuptools-scm",
    { include-group = "lint" },
    { include-group = "test" },
]
build = [
    "build",
    "bump-my-version",
    "setuptools-scm",
    "towncrier",
    "twine",
]
docs = [
    "griffe",
    "mike",
    "mkdocstrings",
    "mkdocstrings-python",
    "zensical",
]
notebooks = [
    "ipykernel<7",
]
lint = [
    "ruff",
]
test = [
    "pytest>=8",
]

[tool.bumpversion]
current_version = "0.4"
commit = false
message = "release version {new_version}"
tag = false
tag_message = "{new_version}"
tag_name = "{new_version}"

[[tool.bumpversion.files]]
filename = "CHANGES.md"
search = """
[unreleased]: https://github.com/tylerh111/pydantic-pint/compare/{current_version}...main
"""
replace = """
[unreleased]: https://github.com/tylerh111/pydantic-pint/compare/{new_version}...main
[{new_version}]: https://github.com/tylerh111/pydantic-pint/releases/tag/{new_version}
"""

[[tool.bumpversion.files]]
filename = "justfile"
search = '_version_fallback := "{current_version}"'
replace = '_version_fallback := "{new_version}"'

[[tool.bumpversion.files]]
filename = "LICENSE.md"
search = "Copyright \\(c\\) 2024-\\d{{4}}"
replace = "Copyright \\(c\\) 2024-{now:%Y}"
regex = true

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'current_version = "{current_version}"'
replace = 'current_version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'fallback_version = "{current_version}"'
replace = 'fallback_version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "zensical.toml"
search = "Copyright &copy; 2024-\\d{{4}}"
replace = "Copyright &copy; 2024-{now:%Y}"
regex = true

[[tool.bumpversion.files]]
filename = "src/pydantic_pint/__init__.py"
search = '__version__ = "{current_version}"'
replace = '__version__ = "{new_version}"'

[tool.coverage.run]
branch = true

[tool.coverage.report]
ignore_errors = true
exclude_also = [
    "def __repr__",
    "if self\\.debug",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__:",
    "@(abc\\.)?abstractmethod",
]

[tool.mypy]
plugins = [
    "pydantic.mypy",
]

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]
pythonpath = "src"

[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py38"

[tool.ruff.lint]
# see rules at https://docs.astral.sh/ruff/rules
extend-select = ["RUF", "C90", "UP", "I", "D"]
extend-ignore = ["D105", "D107", "F541", ]
unfixable = ["B"]
# isort = { known-first-party = ["pydantic-pint"] }
mccabe = { max-complexity = 14 }
pydocstyle = { convention = "google" }

[tool.ruff.lint.isort]
required-imports = ["from __future__ import annotations"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402", "F401"]
"**/{docs,tests,tools}/*" = ["E402", "D"]
"**/notebooks/**/*.ipynb" = ["E402"]
"*.pyi" = ["I002"]

[tool.ruff.format]
quote-style = "double"

[tool.towncrier]
version = "0.4"
directory = "changes"
filename = "CHANGES.md"
start_string = "<!-- release notes -->\n"
underlines = ["", "", ""]
title_format = "## [{version}] ({project_date})"
issue_format = "[{issue}](https://github.com/tylerh111/pydantic-pint/issues/{issue})"
type = [
    { name = "Security", directory = "security", showcontent = true},
    { name = "Removed", directory = "remove", showcontent = true},
    { name = "Deprecated", directory = "deprecated", showcontent = true},
    { name = "Added", directory = "add", showcontent = true},
    { name = "Changed", directory = "change", showcontent = true},
    { name = "Fixed", directory = "fix", showcontent = true},
    { name = "Misc", directory = "misc", showcontent = false },
]

[tool.setuptools_scm]
fallback_version = "0.4"
version_scheme = "no-guess-dev"
write_to = "src/pydantic_pint/_version.py"
